# Jekyll
exclude: nbproject, README.md, manifest.yml, rakefile.rb, Gemfile, Gemfile.lock, update.sh
permalink:   date
url:         http://blog.502Studios.net

safe:        false
auto:        false

future:      false
pygments:    true
markdown:    rdiscount

# Site
uberobert:
    title: 502 Studios

# Only First P Plugin
only_first_p:
    show_read_more_link: true

#analytics for the blog
analytics :
  provider : google
  google : 
      tracking_id : 'UA-39448178-1
'